name: ios_native_sidebar
description: "Native iOS 26's Liquid Glass style sidebar widget for Flutter"
version: 0.0.1
homepage: https://github.com/rivafarabi/ios_native_sidebar
repository: https://github.com/rivafarabi/ios_native_sidebar

environment:
  sdk: ^3.7.2
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: IosNativeSidebarPlugin
